export default {
  sofas: [
    {
      img: require("@/assets/img/products/1.jpg"),
      title: "Угловой диван Атланта Люкс рогожка Malmo серый",
      price: "32 999",
      oldPrice: "39 999",
      sale: "18",
      retings: 5,
      reviews: 15,
    },
    {
      img: require("@/assets/img/products/2.jpg"),
      title: "Угловой диван BOSS XL велюр Alkantara серый",
      price: "68 999",
      oldPrice: "79 999",
      sale: "14",
      retings: 5,
      reviews: 2,
    },
    {
      img: require("@/assets/img/products/3.jpg"),
      title: "Угловой диван BOSS MAX велюр Alkantara серый",
      price: "74 999",
      oldPrice: "99 999",
      sale: "25",
      retings: 5,
      reviews: 6,
    },
  ],
  beds: [
    {
      img: require("@/assets/img/products/4.jpg"),
      title: "Кровать SKANDY Monolit санд",
      price: "34 999",
      oldPrice: "41 999",
      sale: "17",
      retings: 4,
      reviews: 3,
    },
    {
      img: require("@/assets/img/products/5.jpg"),
      title: "Кровать SKANDY Monolit серая",
      price: "34 999",
      oldPrice: "41 999",
      sale: "17",
      retings: 4,
      reviews: 6,
    },
    {
      img: require("@/assets/img/products/6.jpg"),
      title: "Кровать SKANDY Monolit роуз",
      price: "34 999",
      oldPrice: "41 999",
      sale: "17",
      retings: 4,
      reviews: 1,
    },
  ],
  mattresses: [
    {
      img: require("@/assets/img/products/7.jpg"),
      title: "Матрас King 160*200",
      price: "59 999",
      oldPrice: "78 999",
      sale: "24",
      retings: 5,
      reviews: 13,
    },
    {
      img: require("@/assets/img/products/8.jpg"),
      title: "Матрас Комфорт 140*200",
      price: "18 999",
      oldPrice: "19 999",
      sale: "5",
      retings: 4,
      reviews: 10,
    },
    {
      img: require("@/assets/img/products/9.jpg"),
      title: "Матрас Люкс 160*200",
      price: "24 999",
      oldPrice: "81 999",
      sale: "22",
      retings: 5,
      reviews: 7,
    },
  ],
  walls: [
    {
      img: require("@/assets/img/products/10.jpg"),
      title: "Стенка Мальта Венге, Дуб",
      price: "29 999",
      oldPrice: "35 999",
      sale: "19",
      retings: 5,
      reviews: 16,
    },
    {
      img: require("@/assets/img/products/11.jpg"),
      title: "Стенка Монтана Крафт табачный, Серый графит",
      price: "26 999",
      oldPrice: "35 999",
      sale: "25",
      retings: 4,
      reviews: 12,
    },
    {
      img: require("@/assets/img/products/12.jpg"),
      title: "Стенка LUX Сонома, Белый снег",
      price: "15 999",
      oldPrice: "19 999",
      sale: "20",
      retings: 5,
      reviews: 13,
    },
  ],
  cabinets: [
    {
      img: require("@/assets/img/products/13.jpg"),
      title: "Шкаф РИМ-150 Венге, Дуб",
      price: "22 999",
      oldPrice: "28 999",
      sale: "21",
      retings: 5,
      reviews: 29,
    },
    {
      img: require("@/assets/img/products/14.jpg"),
      title: "Шкаф-купе РИМ-120 Сонома, Белый снег",
      price: "22 999",
      oldPrice: "28 999",
      sale: "21",
      retings: 5,
      reviews: 17,
    },
    {
      img: require("@/assets/img/products/15.jpg"),
      title: "ШКАФ BOSS-180 Сонома, Белый глянец",
      price: "38 999",
      oldPrice: "44 999",
      sale: "13",
      retings: 4,
      reviews: 1,
    },
  ],
  kitchens: [
    {
      img: require("@/assets/img/products/16.jpg"),
      title: "Кухонный гарнитур Люкс-200 Сонома",
      price: "22 999",
      oldPrice: "27 999",
      sale: "18",
      retings: 5,
      reviews: 2,
    },
    {
      img: require("@/assets/img/products/17.jpg"),
      title: "Кухонный гарнитур Люкс-120 Лайт Сонома",
      price: "12 999",
      oldPrice: "19 999",
      sale: "35",
      retings: 5,
      reviews: 1,
    },
    {
      img: require("@/assets/img/products/18.jpg"),
      title: "Кухонный гарнитур Люкс-200 Лайт Серый графит",
      price: "19 999",
      oldPrice: "26 999",
      sale: "26",
      retings: 4,
      reviews: 5,
    },
  ],
  tables: [
    {
      img: require("@/assets/img/products/19.jpg"),
      title: "Стол-трансформер LUX венге",
      price: "9 999",
      oldPrice: "14 999",
      sale: "33",
      retings: 5,
      reviews: 15,
    },
    {
      img: require("@/assets/img/products/20.jpg"),
      title: "Обеденный стол Асти, Венге, Ваниль",
      price: "14 999",
      oldPrice: "19 999",
      sale: "25",
      retings: 4,
      reviews: 7,
    },
    {
      img: require("@/assets/img/products/21.jpg"),
      title: "Обеденный стол Асти Ваниль",
      price: "14 999",
      oldPrice: "19 999",
      sale: "25",
      retings: 4,
      reviews: 7,
    },
  ],
  armchairs: [
    {
      img: require("@/assets/img/products/22.jpg"),
      title: "Стул Онтарио велюр Velutto Серый, Черный",
      price: "8 599",
      oldPrice: "9 999",
      sale: "14",
      retings: 5,
      reviews: 1,
    },
    {
      img: require("@/assets/img/products/23.jpg"),
      title: "Стул Онтарио велюр Velutto Синий, Черный",
      price: "8 599",
      oldPrice: "9 999",
      sale: "14",
      retings: 4,
      reviews: 6,
    },
    {
      img: require("@/assets/img/products/24.jpg"),
      title: "Стул НОРД велюр Velutto Бежевый, Белый",
      price: "6 599",
      oldPrice: "8 999",
      sale: "27",
      retings: 5,
      reviews: 3,
    },
  ],
  chairs: [
    {
      img: require("@/assets/img/products/25.jpg"),
      title: "Кресло BOSS Relax велюр Alkantara серый",
      price: "20 999",
      oldPrice: "29 999",
      sale: "30",
      retings: 4,
      reviews: 1,
    },
    {
      img: require("@/assets/img/products/26.png"),
      title: "Кресло-кровать BOSS рогожка Malmo серый",
      price: "24 999",
      oldPrice: "34 999",
      sale: "29",
      retings: 5,
      reviews: 1,
    },
    {
      img: require("@/assets/img/products/27.jpg"),
      title: "Кресло-кровать BOSS шенилл Soro санд",
      price: "25 999",
      oldPrice: "34 999",
      sale: "26",
      retings: 5,
      reviews: 3,
    },
  ],
  nightstands: [
    {
      img: require("@/assets/img/products/28.jpg"),
      title: "2 тумбы КАСЛ Сонома",
      price: "5 999",
      oldPrice: "7 999",
      sale: "25",
      retings: 5,
      reviews: 3,
    },
    {
      img: require("@/assets/img/products/29.jpg"),
      title: "2 тумбы КАСЛ Крафт табачный",
      price: "5 999",
      oldPrice: "7 999",
      sale: "25",
      retings: 4,
      reviews: 2,
    },
    {
      img: require("@/assets/img/products/30.jpg"),
      title: "2 тумбы КАСЛ Венге",
      price: "5 999",
      oldPrice: "7 999",
      sale: "25",
      retings: 5,
      reviews: 1,
    },
  ],
  puffs: [
    {
      img: require("@/assets/img/products/31.png"),
      title: "2 тумбы КАСЛ Сонома",
      price: "11 999",
      oldPrice: "14 999",
      sale: "20",
      retings: 5,
      reviews: 3,
    },
    {
      img: require("@/assets/img/products/32.jpg"),
      title: "2 тумбы КАСЛ Сонома",
      price: "12 999",
      oldPrice: "14 999",
      sale: "13",
      retings: 4,
      reviews: 1,
    },
    {
      img: require("@/assets/img/products/33.png"),
      title: "2 тумбы КАСЛ Сонома",
      price: "13 999",
      oldPrice: "14 999",
      sale: "7",
      retings: 5,
      reviews: 25,
    },
  ],
  dressers: [
    {
      img: require("@/assets/img/products/34.jpg"),
      title: "Комод КАСЛ Сонома",
      price: "6 999",
      oldPrice: "8 999",
      sale: "22",
      retings: 4,
      reviews: 2,
    },
    {
      img: require("@/assets/img/products/35.jpg"),
      title: "Комод КАСЛ Крафт табачный",
      price: "6 999",
      oldPrice: "8 999",
      sale: "22",
      retings: 5,
      reviews: 6,
    },
    {
      img: require("@/assets/img/products/36.jpg"),
      title: "Комод КАСЛ Венге",
      price: "6 999",
      oldPrice: "8 999",
      sale: "22",
      retings: 4,
      reviews: 12,
    },
  ],
  sale: [
    {
      img: require("@/assets/img/products/37.jpg"),
      title: "Диван BOSS рогожка Malmo серый",
      price: "44 999",
      oldPrice: "59 999",
      sale: "26",
      retings: 5,
      reviews: 31,
    },
    {
      img: require("@/assets/img/products/38.jpg"),
      title: "Диван Dandy euro рогожка Malmo бежевый",
      price: "38 999",
      oldPrice: "53 999",
      sale: "28",
      retings: 4,
      reviews: 5,
    },
    {
      img: require("@/assets/img/products/39.jpg"),
      title: "Угловой диван BOSS XL рогожка Malmo серый",
      price: "62 999",
      oldPrice: "79 999",
      sale: "22",
      retings: 5,
      reviews: 25,
    },
  ],
};
